"""empty message

Revision ID: 8b3a72d7c97d
Revises: e7351100ca85
Create Date: 2020-11-13 07:00:24.955633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3a72d7c97d'
down_revision = 'e7351100ca85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ######################solving the inserted null values bug##########################################3
    op.execute("UPDATE artists SET seeking_description = 'Looking for shows to perform at in awesome venues.' WHERE seeking_description IS NULL;")
    op.alter_column('artists', 'seeking_description', nullable=False)
    ######################solving the inserted null values bug##########################################3

    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ######################solving the inserted null values bug##########################################3
    op.execute("UPDATE venues SET seeking_description = 'We are on the lookout for a local artist to play every two weeks. Please call us.' WHERE seeking_description IS NULL;")
    op.alter_column('venues', 'seeking_description', nullable=False)
    ######################solving the inserted null values bug##########################################3
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('artists', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
